# Generated by Django 4.2.16 on 2024-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="booking_photos/"),
        ),
    ]
