# Generated by Django 4.2.16 on 2024-10-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_appointment_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
