# Generated by Django 4.2.16 on 2024-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_appointment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
