# Generated by Django 5.1.6 on 2025-02-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_appointment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
