# Generated by Django 5.1.6 on 2025-03-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_profile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
    ]
